/**
 * Regenerates `src/audioDurations.ts` from the .ogg files in `@udtc/assets`.
 *
 *   node scripts/measure-audio.mjs
 *
 * Why a generated table rather than reading durations in the browser: a group page shows up to 25
 * clips, and the only way to learn a duration at runtime is `preload="metadata"`, which for Ogg
 * costs two range requests per file (the header for the sample rate, the tail for the granule
 * position). Across 115 files that is a few hundred requests to display a number that never
 * changes. `art.test.ts` fails if this table and the audio files disagree, so it cannot go stale
 * quietly.
 *
 * The parse is deliberately dependency-free — Ogg carries the answer in two fixed places:
 *   • sample rate — the Vorbis identification header in the first page.
 *   • total samples — the granule position of the last page.
 * Duration is the second divided by the first.
 */
import { readdirSync, openSync, readSync, closeSync, statSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const AUDIO_DIR = join(HERE, '../../../packages/assets/audio');
const OUT = join(HERE, '../src/audioDurations.ts');

/** An unset granule position — a page that carries no timing information. */
const NO_GRANULE = 0xffffffffffffffffn;

function read(fd, length, position) {
  const buf = Buffer.alloc(length);
  const got = readSync(fd, buf, 0, length, position);
  return buf.subarray(0, got);
}

function durationSeconds(path) {
  const fd = openSync(path, 'r');
  try {
    // Page header is 27 bytes + one byte per segment; the identification header packet follows.
    const head = read(fd, 128, 0);
    if (head.subarray(0, 4).toString('latin1') !== 'OggS') throw new Error('not an Ogg stream');
    const packet = 27 + head[26];
    if (head.subarray(packet, packet + 7).toString('latin1') !== 'vorbis') {
      throw new Error('not Ogg Vorbis');
    }
    // Identification header: type(1) magic(6) version(4) channels(1) rate(4, LE).
    const rate = head.readUInt32LE(packet + 12);

    // The last page's granule position is the stream's total sample count. Scan the tail backwards
    // for it: a page can legitimately carry NO_GRANULE, so keep walking until one does not.
    const size = statSync(path).size;
    const start = Math.max(0, size - 65536);
    const tail = read(fd, size - start, start);
    for (let i = tail.length - 27; i >= 0; i--) {
      if (tail.readUInt32BE(i) !== 0x4f676753) continue; // 'OggS'
      const granule = tail.readBigUInt64LE(i + 6);
      if (granule !== NO_GRANULE) return Number(granule) / rate;
    }
    throw new Error('no page carried a granule position');
  } finally {
    closeSync(fd);
  }
}

const files = readdirSync(AUDIO_DIR)
  .filter((f) => f.endsWith('.ogg'))
  .sort();
if (files.length === 0) throw new Error(`no .ogg files under ${AUDIO_DIR}`);

const rows = files.map((f) => `  '${f}': ${durationSeconds(join(AUDIO_DIR, f)).toFixed(2)},`);

writeFileSync(
  OUT,
  `// GENERATED by scripts/measure-audio.mjs — do not edit by hand.
// Clip length in seconds, keyed by filename. Regenerate after adding or replacing audio;
// \`art.test.ts\` fails until this table matches the files in @udtc/assets.
export const AUDIO_SECONDS: Record<string, number> = {
${rows.join('\n')}
};
`,
);

console.log(`measure-audio: wrote ${files.length} durations to ${OUT}`);
