// The official tower sound library, resolved to bundler-emitted URLs.
//
// AUTOGENERATED by `packages/display/scripts/extract-audio.mjs` — do not hand-edit the table.
// That script owns both halves of the split: the sample-id → filename map in
// `packages/display/src/audio/audioLibrary.ts` and the filename → URL map here.
//
// Keyed by **filename**, not by sample id, so this package stays dependency-free: the id enum
// lives in `ultimatedarktower`, and importing it here would couple the art package to the
// driver. `audioLibrary.ts` joins the two maps.
//
// Per-file `new URL('<literal>', import.meta.url).href` is deliberate and is NOT interchangeable
// with the `import.meta.glob` used for tokens. Under Vite's *library* mode a glob resolves to a
// static string — verified: `/Adversary_Ashstrider_01.ogg`, absolute and base-less — whereas this
// shape survives as `new URL(..., import.meta.url)` in the emitted bundle, which is what keeps
// the URL relative to the chunk at runtime and re-detectable by each consumer's own bundler.
// Every app in this repo re-emits its own copies of these files that way. Do not "simplify" it
// to a glob.
//
// See also `packages/display/vite.config.ts` → URL_ASSET_HOSTS: display's library build has to
// intercept these expressions, or lib mode base64-inlines 8 MB of audio into the bundle.

/** Official sound-library filename (e.g. `'Battle_Victory_01.ogg'`) → bundled URL. */
export const audioUrls: Record<string, string> = {
  // === BEGIN AUTOGEN (packages/display/scripts/extract-audio.mjs) ===
  'Adversary_Ashstrider_01.ogg': new URL('../../audio/Adversary_Ashstrider_01.ogg', import.meta.url)
    .href,
  'Adversary_Bane_01.ogg': new URL('../../audio/Adversary_Bane_01.ogg', import.meta.url).href,
  'Adversary_Empress_01.ogg': new URL('../../audio/Adversary_Empress_01.ogg', import.meta.url).href,
  'Adversary_Gaze_01.ogg': new URL('../../audio/Adversary_Gaze_01.ogg', import.meta.url).href,
  'Adversary_Gravemaw_01.ogg': new URL('../../audio/Adversary_Gravemaw_01.ogg', import.meta.url)
    .href,
  'Adversary_Isa_01.ogg': new URL('../../audio/Adversary_Isa_01.ogg', import.meta.url).href,
  'Adversary_Rot_03.ogg': new URL('../../audio/Adversary_Rot_03.ogg', import.meta.url).href,
  'Adversary_Utuk_03.ogg': new URL('../../audio/Adversary_Utuk_03.ogg', import.meta.url).href,
  'Ally_Gleb_01.ogg': new URL('../../audio/Ally_Gleb_01.ogg', import.meta.url).href,
  'Ally_Grigor_01.ogg': new URL('../../audio/Ally_Grigor_01.ogg', import.meta.url).href,
  'Ally_Hakan_02.ogg': new URL('../../audio/Ally_Hakan_02.ogg', import.meta.url).href,
  'Ally_Letha_02.ogg': new URL('../../audio/Ally_Letha_02.ogg', import.meta.url).href,
  'Ally_Miras_01.ogg': new URL('../../audio/Ally_Miras_01.ogg', import.meta.url).href,
  'Ally_Nimet_01.ogg': new URL('../../audio/Ally_Nimet_01.ogg', import.meta.url).href,
  'Ally_Tomas_03.ogg': new URL('../../audio/Ally_Tomas_03.ogg', import.meta.url).href,
  'Ally_Vasa_03.ogg': new URL('../../audio/Ally_Vasa_03.ogg', import.meta.url).href,
  'Ally_Yana_01.ogg': new URL('../../audio/Ally_Yana_01.ogg', import.meta.url).href,
  'Ally_Zaida_01.ogg': new URL('../../audio/Ally_Zaida_01.ogg', import.meta.url).href,
  'Battle_Advantage_Applied_01.ogg': new URL(
    '../../audio/Battle_Advantage_Applied_01.ogg',
    import.meta.url,
  ).href,
  'Battle_Advantage_Applied_02.ogg': new URL(
    '../../audio/Battle_Advantage_Applied_02.ogg',
    import.meta.url,
  ).href,
  'Battle_Advantage_Applied_03.ogg': new URL(
    '../../audio/Battle_Advantage_Applied_03.ogg',
    import.meta.url,
  ).href,
  'Battle_Advantage_Applied_04.ogg': new URL(
    '../../audio/Battle_Advantage_Applied_04.ogg',
    import.meta.url,
  ).href,
  'Battle_Advantage_Applied_05.ogg': new URL(
    '../../audio/Battle_Advantage_Applied_05.ogg',
    import.meta.url,
  ).href,
  'Battle_Advantages_Maxed_01.ogg': new URL(
    '../../audio/Battle_Advantages_Maxed_01.ogg',
    import.meta.url,
  ).href,
  'Battle_Advantages_None_01.ogg': new URL(
    '../../audio/Battle_Advantages_None_01.ogg',
    import.meta.url,
  ).href,
  'Battle_Adversary_Escape_01.ogg': new URL(
    '../../audio/Battle_Adversary_Escape_01.ogg',
    import.meta.url,
  ).href,
  'Battle_Button_01.ogg': new URL('../../audio/Battle_Button_01.ogg', import.meta.url).href,
  'Battle_Card_Flip_01.ogg': new URL('../../audio/Battle_Card_Flip_01.ogg', import.meta.url).href,
  'Battle_Card_Flip_02.ogg': new URL('../../audio/Battle_Card_Flip_02.ogg', import.meta.url).href,
  'Battle_Card_Flip_03.ogg': new URL('../../audio/Battle_Card_Flip_03.ogg', import.meta.url).href,
  'Battle_Card_Flip_Paper_01.ogg': new URL(
    '../../audio/Battle_Card_Flip_Paper_01.ogg',
    import.meta.url,
  ).href,
  'Battle_Card_Flip_Paper_02.ogg': new URL(
    '../../audio/Battle_Card_Flip_Paper_02.ogg',
    import.meta.url,
  ).href,
  'Battle_Card_Flip_Paper_03.ogg': new URL(
    '../../audio/Battle_Card_Flip_Paper_03.ogg',
    import.meta.url,
  ).href,
  'Battle_Card_Select_01.ogg': new URL('../../audio/Battle_Card_Select_01.ogg', import.meta.url)
    .href,
  'Battle_Card_Select_02.ogg': new URL('../../audio/Battle_Card_Select_02.ogg', import.meta.url)
    .href,
  'Battle_Card_Select_03.ogg': new URL('../../audio/Battle_Card_Select_03.ogg', import.meta.url)
    .href,
  'Battle_Victory_01.ogg': new URL('../../audio/Battle_Victory_01.ogg', import.meta.url).href,
  'Battle_start_01.ogg': new URL('../../audio/Battle_start_01.ogg', import.meta.url).href,
  'Button_Hold_01.ogg': new URL('../../audio/Button_Hold_01.ogg', import.meta.url).href,
  'Button_HoldandPressComboDemo.ogg': new URL(
    '../../audio/Button_HoldandPressComboDemo.ogg',
    import.meta.url,
  ).href,
  'Button_Press_01.ogg': new URL('../../audio/Button_Press_01.ogg', import.meta.url).href,
  'Classic_AdvantageApplied.ogg': new URL(
    '../../audio/Classic_AdvantageApplied.ogg',
    import.meta.url,
  ).href,
  'Classic_Attack_Tower.ogg': new URL('../../audio/Classic_Attack_Tower.ogg', import.meta.url).href,
  'Classic_Bazaar.ogg': new URL('../../audio/Classic_Bazaar.ogg', import.meta.url).href,
  'Classic_Confirmation_Beep.ogg': new URL(
    '../../audio/Classic_Confirmation_Beep.ogg',
    import.meta.url,
  ).href,
  'Classic_DragonStrike.ogg': new URL('../../audio/Classic_DragonStrike.ogg', import.meta.url).href,
  'Classic_Quest_Failure.ogg': new URL('../../audio/Classic_Quest_Failure.ogg', import.meta.url)
    .href,
  'Classic_Retreat.ogg': new URL('../../audio/Classic_Retreat.ogg', import.meta.url).href,
  'Classic_StartOfMonth.ogg': new URL('../../audio/Classic_StartOfMonth.ogg', import.meta.url).href,
  'Classic_StartingDungeon.ogg': new URL('../../audio/Classic_StartingDungeon.ogg', import.meta.url)
    .href,
  'Classic_TowerLost.ogg': new URL('../../audio/Classic_TowerLost.ogg', import.meta.url).href,
  'Classic_Unsure_5.ogg': new URL('../../audio/Classic_Unsure_5.ogg', import.meta.url).href,
  'Dungeon_Advantage_01.ogg': new URL('../../audio/Dungeon_Advantage_01.ogg', import.meta.url).href,
  'Dungeon_Advantage_02.ogg': new URL('../../audio/Dungeon_Advantage_02.ogg', import.meta.url).href,
  'Dungeon_Button_01.ogg': new URL('../../audio/Dungeon_Button_01.ogg', import.meta.url).href,
  'Dungeon_Button_Footsteps_01.ogg': new URL(
    '../../audio/Dungeon_Button_Footsteps_01.ogg',
    import.meta.url,
  ).href,
  'Dungeon_Caves_01.ogg': new URL('../../audio/Dungeon_Caves_01.ogg', import.meta.url).href,
  'Dungeon_Complete_01.ogg': new URL('../../audio/Dungeon_Complete_01.ogg', import.meta.url).href,
  'Dungeon_Encampment_01.ogg': new URL('../../audio/Dungeon_Encampment_01.ogg', import.meta.url)
    .href,
  'Dungeon_Escape_01.ogg': new URL('../../audio/Dungeon_Escape_01.ogg', import.meta.url).href,
  'Dungeon_Fortress_01.ogg': new URL('../../audio/Dungeon_Fortress_01.ogg', import.meta.url).href,
  'Dungeon_Ruins_01.ogg': new URL('../../audio/Dungeon_Ruins_01.ogg', import.meta.url).href,
  'Dungeon_Shrine_01.ogg': new URL('../../audio/Dungeon_Shrine_01.ogg', import.meta.url).href,
  'Dungeon_Tomb_01.ogg': new URL('../../audio/Dungeon_Tomb_01.ogg', import.meta.url).href,
  'Event_Foe.ogg': new URL('../../audio/Event_Foe.ogg', import.meta.url).href,
  'Event_Spawn.ogg': new URL('../../audio/Event_Spawn.ogg', import.meta.url).href,
  'Foe_Brigands_03.ogg': new URL('../../audio/Foe_Brigands_03.ogg', import.meta.url).href,
  'Foe_Clan_01.ogg': new URL('../../audio/Foe_Clan_01.ogg', import.meta.url).href,
  'Foe_Dragon_01.ogg': new URL('../../audio/Foe_Dragon_01.ogg', import.meta.url).href,
  'Foe_Lemure_01.ogg': new URL('../../audio/Foe_Lemure_01.ogg', import.meta.url).href,
  'Foe_Level_Up_01.ogg': new URL('../../audio/Foe_Level_Up_01.ogg', import.meta.url).href,
  'Foe_Mormo_01.ogg': new URL('../../audio/Foe_Mormo_01.ogg', import.meta.url).href,
  'Foe_Oreks_01.ogg': new URL('../../audio/Foe_Oreks_01.ogg', import.meta.url).href,
  'Foe_Shadow_01.ogg': new URL('../../audio/Foe_Shadow_01.ogg', import.meta.url).href,
  'Foe_Spine_01.ogg': new URL('../../audio/Foe_Spine_01.ogg', import.meta.url).href,
  'Foe_Striga_01.ogg': new URL('../../audio/Foe_Striga_01.ogg', import.meta.url).href,
  'Foe_Titan_01.ogg': new URL('../../audio/Foe_Titan_01.ogg', import.meta.url).href,
  'Foe_Troll_01.ogg': new URL('../../audio/Foe_Troll_01.ogg', import.meta.url).href,
  'Foe_Widowmade_01.ogg': new URL('../../audio/Foe_Widowmade_01.ogg', import.meta.url).href,
  'MainObjectiveVictory_BossSpawn_Ashstrider.ogg': new URL(
    '../../audio/MainObjectiveVictory_BossSpawn_Ashstrider.ogg',
    import.meta.url,
  ).href,
  'MainObjectiveVictory_BossSpawn_Bane.ogg': new URL(
    '../../audio/MainObjectiveVictory_BossSpawn_Bane.ogg',
    import.meta.url,
  ).href,
  'MainObjectiveVictory_BossSpawn_Empress.ogg': new URL(
    '../../audio/MainObjectiveVictory_BossSpawn_Empress.ogg',
    import.meta.url,
  ).href,
  'MainObjectiveVictory_BossSpawn_Gaze.ogg': new URL(
    '../../audio/MainObjectiveVictory_BossSpawn_Gaze.ogg',
    import.meta.url,
  ).href,
  'MainObjectiveVictory_BossSpawn_Gravemaw.ogg': new URL(
    '../../audio/MainObjectiveVictory_BossSpawn_Gravemaw.ogg',
    import.meta.url,
  ).href,
  'MainObjectiveVictory_BossSpawn_Isa.ogg': new URL(
    '../../audio/MainObjectiveVictory_BossSpawn_Isa.ogg',
    import.meta.url,
  ).href,
  'MainObjectiveVictory_BossSpawn_Rot.ogg': new URL(
    '../../audio/MainObjectiveVictory_BossSpawn_Rot.ogg',
    import.meta.url,
  ).href,
  'MainObjectiveVictory_BossSpawn_Utuk.ogg': new URL(
    '../../audio/MainObjectiveVictory_BossSpawn_Utuk.ogg',
    import.meta.url,
  ).href,
  'Quest_Complete_01.ogg': new URL('../../audio/Quest_Complete_01.ogg', import.meta.url).href,
  'Tower_All_Glyphs_01.ogg': new URL('../../audio/Tower_All_Glyphs_01.ogg', import.meta.url).href,
  'Tower_Angry_01.ogg': new URL('../../audio/Tower_Angry_01.ogg', import.meta.url).href,
  'Tower_Angry_02.ogg': new URL('../../audio/Tower_Angry_02.ogg', import.meta.url).href,
  'Tower_Angry_03.ogg': new URL('../../audio/Tower_Angry_03.ogg', import.meta.url).href,
  'Tower_Angry_04.ogg': new URL('../../audio/Tower_Angry_04.ogg', import.meta.url).href,
  'Tower_Connected_04.ogg': new URL('../../audio/Tower_Connected_04.ogg', import.meta.url).href,
  'Tower_Game_Start.ogg': new URL('../../audio/Tower_Game_Start.ogg', import.meta.url).href,
  'Tower_Gloat_01.ogg': new URL('../../audio/Tower_Gloat_01.ogg', import.meta.url).href,
  'Tower_Gloat_02.ogg': new URL('../../audio/Tower_Gloat_02.ogg', import.meta.url).href,
  'Tower_Gloat_03.ogg': new URL('../../audio/Tower_Gloat_03.ogg', import.meta.url).href,
  'Tower_Glyph_01.ogg': new URL('../../audio/Tower_Glyph_01.ogg', import.meta.url).href,
  'Tower_Idle_01.ogg': new URL('../../audio/Tower_Idle_01.ogg', import.meta.url).href,
  'Tower_Idle_02.ogg': new URL('../../audio/Tower_Idle_02.ogg', import.meta.url).href,
  'Tower_Idle_03.ogg': new URL('../../audio/Tower_Idle_03.ogg', import.meta.url).href,
  'Tower_Idle_04.ogg': new URL('../../audio/Tower_Idle_04.ogg', import.meta.url).href,
  'Tower_Idle_05.ogg': new URL('../../audio/Tower_Idle_05.ogg', import.meta.url).href,
  'Tower_Lost_Connection_04.ogg': new URL(
    '../../audio/Tower_Lost_Connection_04.ogg',
    import.meta.url,
  ).href,
  'Tower_Month_End_06.ogg': new URL('../../audio/Tower_Month_End_06.ogg', import.meta.url).href,
  'Tower_Month_Start_01.ogg': new URL('../../audio/Tower_Month_Start_01.ogg', import.meta.url).href,
  'Tower_Quest_Failure.ogg': new URL('../../audio/Tower_Quest_Failure.ogg', import.meta.url).href,
  'Tower_Rotate_Exit.ogg': new URL('../../audio/Tower_Rotate_Exit.ogg', import.meta.url).href,
  'Tower_Rotate_Loop.ogg': new URL('../../audio/Tower_Rotate_Loop.ogg', import.meta.url).href,
  'Tower_Rotate_Start.ogg': new URL('../../audio/Tower_Rotate_Start.ogg', import.meta.url).href,
  'Tower_Seal_01.ogg': new URL('../../audio/Tower_Seal_01.ogg', import.meta.url).href,
  'Tower_Skull_Drop_01.ogg': new URL('../../audio/Tower_Skull_Drop_01.ogg', import.meta.url).href,
  // === END AUTOGEN ===
};
