// Behavioural parity between the pre-0.5.0 bucketed `BoardState` and the current one,
// driven through the controller's convenience methods (the surface that survives the
// refactor — see the class doc on `BoardStateController`). `fixtures/v1-parity.json` is a
// frozen snapshot of the OLD reducer/controller's output after each step in a fixed call
// sequence (generated by `fixtures/gen-v1-parity.mjs`, a transliteration of the pre-0.5.0
// source — see that file's header for provenance). This test replays the SAME sequence
// through the CURRENT controller and asserts the state, read through the new selectors,
// reconstructs the identical old-shaped snapshot at every step.
//
// This is what keeps "the reducer enforces no rules and never throws" — the package's
// central documented invariant — from quietly regressing during a refactor this size.
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { BoardStateController } from '../src/index';
import {
  adversaryOf,
  buildingAt,
  foesOf,
  heroesOf,
  monumentAt,
  skullsAt,
} from '../src/state/selectors';
import type { BoardState } from '../src/index';

const here = dirname(fileURLToPath(import.meta.url));

interface OldBuilding {
  skulls: number;
  destroyed: boolean;
  monument?: string;
}
interface OldShape {
  heroes: Record<string, { location: string; owner?: string }>;
  foes: Record<string, { foe: string; location: string; status: string }>;
  adversary?: { id: string; location?: string };
  buildings: Record<string, OldBuilding>;
  spaceMarkers: Record<string, string[]>;
  questMarkers: Record<string, string[]>;
  selections?: BoardState['selections'];
}

interface Step {
  label: string;
  state: OldShape;
}

const fixture = JSON.parse(
  readFileSync(resolve(here, 'fixtures/v1-parity.json'), 'utf8'),
) as Step[];

/**
 * The one disclosed, behaviour-neutral divergence: the old reducer's `setMonument(loc, null)`
 * wrote `monument: null` into the (always-present) building record, distinguishing "cleared"
 * from "never touched" (key absent). The new model deletes the monument token on clear, so
 * that distinction has no representation — and no consumer ever cared: every reader (readout,
 * the inspector, the palette) treats `null`/`undefined`/absent identically (falsy check or
 * `??`). Strip `monument: null` from both sides before comparing so this is a no-op, not a
 * failure — everything else about parity stays a strict `toEqual`.
 */
function stripNullMonument(shape: OldShape): OldShape {
  const buildings: OldShape['buildings'] = {};
  for (const [loc, b] of Object.entries(shape.buildings)) {
    if (b.monument === null) {
      const { monument: _drop, ...rest } = b;
      buildings[loc] = rest;
    } else {
      buildings[loc] = b;
    }
  }
  return { ...shape, buildings };
}

/** Reconstruct the old bucketed shape from the current state, via the public selectors. */
function toOldShape(state: BoardState): OldShape {
  const heroes: OldShape['heroes'] = {};
  for (const h of heroesOf(state)) {
    const owner = h.data?.owner as string | undefined;
    heroes[h.id] = owner !== undefined ? { location: h.location, owner } : { location: h.location };
  }

  const foes: OldShape['foes'] = {};
  for (const f of foesOf(state)) {
    foes[f.id] = {
      foe: f.art ?? '',
      location: f.location,
      status: (f.data?.status as string) ?? 'ready',
    };
  }

  // A "buildings" entry exists for any location the OLD code would have synthesized one for:
  // any location carrying a building OR skull token (the two are split in the new model but
  // were one record in the old one).
  const buildingLocs = new Set<string>();
  for (const t of Object.values(state.tokens)) {
    if (t.typeId === 'building' || t.typeId === 'skull' || t.typeId === 'monument') {
      buildingLocs.add(t.location);
    }
  }
  const buildings: OldShape['buildings'] = {};
  for (const loc of buildingLocs) {
    const b: OldBuilding = {
      skulls: skullsAt(state, loc),
      destroyed: buildingAt(state, loc).destroyed,
    };
    const monument = monumentAt(state, loc);
    if (monument !== undefined) b.monument = monument;
    buildings[loc] = b;
  }

  const spaceMarkers: OldShape['spaceMarkers'] = {};
  const questMarkers: OldShape['questMarkers'] = {};
  for (const t of Object.values(state.tokens)) {
    if (t.typeId === 'marker') {
      (spaceMarkers[t.location] ??= []).push(t.art ?? t.id);
    } else if (t.typeId === 'quest') {
      (questMarkers[t.location] ??= []).push(t.art ?? t.id);
    }
  }

  const adversary = adversaryOf(state);

  return {
    heroes,
    foes,
    ...(adversary !== undefined ? { adversary } : {}),
    buildings,
    spaceMarkers,
    questMarkers,
    ...(state.selections !== undefined ? { selections: state.selections } : {}),
  };
}

describe('controller parity — pre-0.5.0 behaviour, replayed against the current controller', () => {
  it(`matches the frozen v1 baseline at every one of its ${fixture.length} steps`, () => {
    const c = new BoardStateController();
    const A = 'Broken Lands';
    const B = 'Dayside';
    const C = "Egan's End";

    const actions: Array<() => void> = [
      () => {}, // initial
      () => c.placeHero('h1', A, 'north'),
      () => c.placeHero('h2', B),
      () => c.moveHero('h1', B),
      () => c.moveHero('nope', A),
      () => c.removeHero('h2'),
      () => c.removeHero('nope'),
      () => c.spawnFoe('f1', 'Brigands', A),
      () => c.spawnFoe('f2', 'Oreks', B, 'lethal'),
      () => c.moveFoe('f1', B),
      () => c.moveFoe('nope', A),
      () => c.setFoeStatus('f1', 'savage'),
      () => c.setFoeStatus('nope', 'savage'),
      () => c.removeFoe('f2'),
      () => c.removeFoe('nope'),
      () => c.selectAdversary('utuk-ku'),
      () => c.placeAdversary(B),
      () => c.clearAdversary(),
      () => c.placeAdversary(A),
      () => c.selectAdversary('gravemaw'),
      () => c.addSkull(B),
      () => c.addSkull(B, 2),
      () => c.addSkull(B),
      () => c.removeSkull(B, 10),
      () => c.setSkulls(B, 7),
      () => c.destroyBuilding(B),
      () => c.restoreBuilding(B),
      () => c.setMonument(C, 'argent-oak'),
      () => c.setMonument(C, null),
      () => c.addSkull('Nowhere Real', 2),
      () => c.setSpaceMarker(A, 'wasteland', true),
      () => c.setSpaceMarker(A, 'wasteland', true),
      () => c.setSpaceMarker(A, 'power-skull', true),
      () => c.setSpaceMarker(A, 'wasteland', false),
      () => c.setSpaceMarker(A, 'nope', false),
      () => c.setSpaceMarker(A, 'power-skull', false),
      () => c.setQuestMarker(B, 'main-goal', true),
      () => c.setQuestMarker(B, 'main-goal', true),
      () => c.setQuestMarker(B, 'main-goal', false),
      () => c.setSelections({ difficulty: 'Heroic', allies: ['a1'] }),
      () => c.setSelections({ difficulty: 'Gritty' }),
      () => c.reset(),
    ];

    expect(actions).toHaveLength(fixture.length);

    actions.forEach((act, i) => {
      act();
      expect(toOldShape(c.getState())).toEqual(stripNullMonument(fixture[i].state));
    });
  });
});
